# train_test split

## Import the relevent libraries

In [1]:
from sklearn.model_selection import train_test_split 
import numpy as np

## Generate some data we are going to split

In [2]:
a=np.arange(1,101)

In [3]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
b=np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

## Split the data

In [5]:
a_train,a_test,b_train,b_test=train_test_split(a,b,shuffle=True,test_size=0.15) #randomstate=xxx, used for keeping shuffle constant.

In [6]:
a_train,a_train.shape

(array([53, 54, 24,  8, 96, 36, 80,  9, 62, 71, 33, 78, 76, 21, 90, 69, 99,
        30, 89, 35, 26, 23, 50, 92, 81, 93, 79, 66,  1, 58,  4, 40, 91, 55,
        82, 83, 32,  3, 41, 31, 11, 52,  7, 49, 19, 28, 44, 47,  2, 73, 13,
        20, 65, 75, 14, 56, 63, 12, 98, 34, 43, 94, 29, 57, 64, 86, 18, 85,
        46,  5, 38, 15,  6, 59, 95, 48, 77, 42, 84, 61, 74, 88, 60, 16, 10]),
 (85,))

In [7]:
a_test,a_test.shape

(array([ 51,  70,  67,  68,  97, 100,  22,  27,  17,  87,  37,  45,  25,
         39,  72]),
 (15,))

In [8]:
b_train

array([553, 554, 524, 508, 596, 536, 580, 509, 562, 571, 533, 578, 576,
       521, 590, 569, 599, 530, 589, 535, 526, 523, 550, 592, 581, 593,
       579, 566, 501, 558, 504, 540, 591, 555, 582, 583, 532, 503, 541,
       531, 511, 552, 507, 549, 519, 528, 544, 547, 502, 573, 513, 520,
       565, 575, 514, 556, 563, 512, 598, 534, 543, 594, 529, 557, 564,
       586, 518, 585, 546, 505, 538, 515, 506, 559, 595, 548, 577, 542,
       584, 561, 574, 588, 560, 516, 510])

In [9]:
b_test

array([551, 570, 567, 568, 597, 600, 522, 527, 517, 587, 537, 545, 525,
       539, 572])